### ISSUE TITLE
Design change to allow per-backend options

### ISSUE THREAD

**Issue by lox** [99designs/keyring#8]
At the minute it's hard to set per-backend global options like a passphrase (the `file` provider), or per-Item options like "synchronize to keychain", or "only store on this device". I'd like to change the API for accessing keyring to make this possible, ideally in a typesafe way that works with the per-platform conditional compilation. These are some options I'm considering, would love feedback.

### keyring.Options struct

This would move to a structure more like the `[aws.Config](https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config)]`:

```go

opts := keyring.NewOptions().
  WithDefaultKeychain().
  WithFilePassword("llamas rock").
  WithAllowedBackends(keyring.KeychainBackend, keyring.FileBackend)
  
kr, err := keyring.Open("aws-vault", opts)
```

### Typed keyrings

The advantage of this approach is it keeps extensions within the scope of the objects. It increases complexity in that you have to have the provider implemented in a globally compiled file with the per-platform stuff conditionally compiled in a different file. Not sure how possible that would be.

```go
kr, _ := keyring.Open("aws-vault", func(k keyring.Provider) {
  if keychain, ok := kr.(keyring.KeychainBackend); ok {
    kr.SetKeychain("login")
  }
})

kr, _ := keyring.OpenWithPreference("aws-vault", 
  []keyring.Backend{keyring.KeychainBackend, keyring.FileBackend},
  func(k keyring.Provider) bool{
    // ...
  }
})
```

### Use a context and string based keys

You could also use the context for cancellation I guess. I'm still not sold on our context overlords.

```go
ctx := context.Background()

for k, v := range map[string]interface{}{
  "name": "aws-vault",
  "keychain.name": "login",
  "file.passphrase": "llamas rock".
} {
  ctx = context.WithValue(ctx, k, v)
}

kr, _ := keyring.Open(ctx)
```

**Comment by Vektah** [comment]
> keyring.Options struct

:+1: for the fat struct approach. Can we keep the struct open to be used directly rather than with a fluent builder? It also makes it easy to json marshall etc.

> Typed keyrings

I dont know if there is much of an advantage to typed keyrings given you probably need to specify all options for all providers if you want to support.

> Use a context and string based keys
I'm also not a fan of abusing context for config. You lose all type safety and add a bunch of indirection without gaining anything. Also untyped string keys are inviting collisions, what if something else is using "name"?



A fourth approach would be to remove the preference logic and let the caller instantiate the implementations directly. Full type safety.

the caller would end up looking like:
```go
if ring, err := keyring.OpenKeychain("aws-vault", "login") ; err == nil {
   return ring
}

if ring, err := keyring.OpenFile("aws-vault", "llamas rock") ; err == nil {
   return ring
}
```

Conditional compilation would need to build methods that return errors when the real code isnt built:
```go
keychain_osx.go
//build osx
func OpenKeychain(...) (ring, err) {
    ... real code
}

keychain_notosx.go
//!build osx

func OpenKeychain(...) (ring, err) {
    return nil, errors.new("Keychain only available on OSX")
}
```

**Comment by lox** [comment]
Yeah, we'd have a flat struct under the fluent stuff. I'd probably start with that and only add the fluent stuff if needed. 

It would certainly be nice to be able to directly instantiate them if you wanted. Perhaps we are approaching this the wrong way and should have some sort of finder that operates across several possible Keyring objects.
